version: '2.1'

services:
  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=asteroids
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      timeout: 5s
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - '.:/usr/src/app'
    environment:
      - ENVIRONMENT=LOCAL
      - LOG_LEVEL=INFO
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=secret
      - PG_DB_NAME=asteroids
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - API_KEY_NASA=BxfuK34p9pwr6YxtLwpTLSbVxlWYtpmcY63XhPH8
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy