version: '2.1'

services:
  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=asteroids
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      timeout: 5s
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - '.:/usr/src/app'
    environment:
      - ENVIRONMENT=LOCAL
      - LOG_LEVEL=INFO
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=secret
      - PG_DB_NAME=asteroids
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOAD_ASTEROIDS_DATA_INTERVAL=3600
      - LOAD_ASTEROIDS_PAGE_CONCURRENCY=50
      - LOAD_ASTEROID_MAX_PAGES_FOR_LOADING=2
      - API_KEYS_NASA=BxfuK34p9pwr6YxtLwpTLSbVxlWYtpmcY63XhPH8,TiH25Axrnk13ETPaIb2N23fsmr6P5GwWUKRLPmYy,W0yuQzYtDJRSYqkXV4Wvjz6x8gkwOosx1dGaL09X,hjVfcvd9gVwik6oHm2PIOY60Qz3A1sMomRCqflxG
      - URL_NASA_ASTEROIDS=https://api.nasa.gov/neo/rest/v1/neo/browse
      - UPLOAD_FOLDER_NAME=uploaded_images
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy