version: '2.1'

services:
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - '.:/usr/src/app'
    environment:
      - ENVIRONMENT=LOCAL
      - LOG_LEVEL=INFO
    depends_on:
      - db
